### ISSUE TITLE
Add a macro to expand Option<T> in format!?

### ISSUE THREAD

**Issue by kanetkarster** [sacooper/Rust-OAuth#4]
I was playing around instead of studying and was wondering if you wanted to replace stuff like [this](https://github.com/sacooper/Rust-OAuth/blob/a1fc195e71b80889f7f48af14f66d0d7731477d8/src/oauth1/client/session.rs#L71) with a macro like the following:

``` rust
macro_rules! exists(($name : expr, $inp : ident ) => (
                match $ inp {
                None => String::new() , 
                Some ( r ) => {format ! ( "{}=\"{}\"",$name , r ) } 
                }
            ) ;
        );

fn main() { 
    let oauth_realm = Some("test"); 
    println!("{}",exists!("Realm", oauth_realm)); // => Realm="test"
}
```

If we do this, I feel like there is a way to get `$name` from a `format!` parameter and to part of the slice

**Comment by sacooper** [comment]
I like the idea of it. What do you mean by the last part though with getting the name from the format! parameter?

**Comment by kanetkarster** [comment]
I feel like after the macro expansion it should be like `format!("Realm={}", oauth_realm)`

**Comment by sacooper** [comment]
I agree, except for the sake of generality I'd rather it be something along the lines `exists!("Realm=", oauth_realm)` which expands to `format!("Realm={}", oauth_realm.unwrap())`

**Comment by sacooper** [comment]
Also, maybe having the string for `exists!` be `"Realm={}"`, so the actual format string

**Comment by kanetkarster** [comment]
Good call, this works properly

``` rust
macro_rules! exists(($name : expr, $inp : ident ) => 
            (
                match $ inp {
                None => String::new() , 
                Some ( r ) => {format! ( $name, r ) } 
                }
            ) ;
        );

fn main() { 
    let oauth_realm = Some("test"); 
    println!("{}",exists!("Realm={}", oauth_realm));
}
```

**Comment by kanetkarster** [comment]
We don't need to do anything about the unwrap part though, it's taken care of in the macro expansion. You have to use the compiler flag `rustc -Z unstable-options --pretty=expanded` to see it.

**Comment by sacooper** [comment]
Looks good. Lets go for it.
